# Generated by Django 3.1.5 on 2021-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("home", "0002_article_author")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        )
    ]
